(package "ts-docstr"
         "0.1.0"
         "A document string minor mode using tree-sitter")

(website-url "https://github.com/emacs-vs/ts-docstr")
(keywords "convenience")

(package-file "ts-docstr.el")

(source "jcs-elpa")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "tree-sitter")
(depends-on "s")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
